version: "3.9"

services:

  external-service-a:
    image: wiremock/wiremock:2.32.0
    ports:
      - "8081:8080"
    command:
      - "--global-response-templating"
    volumes:
      - ./wiremock/foo-api:/home/wiremock

  external-service-b:
    image: wiremock/wiremock:2.32.0
    ports:
      - "8082:8080"
    command:
      - "--global-response-templating"
    volumes:
      - ./wiremock/bar-api:/home/wiremock